# Generated by Django 4.0.6 on 2022-07-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='jira_id',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='slack_id',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
