# Generated by Django 4.0.6 on 2022-07-26 19:14

import check_in.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0002_alter_person_jira_id_alter_person_slack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_in',
            name='date',
            field=models.DateField(default=check_in.models.check_in.getCurrentDate),
        ),
        migrations.AddField(
            model_name='check_in',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='blockers',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='feeling',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='planned_work',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='prior_work',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='submitted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
