# Generated by Django 4.0.6 on 2022-07-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0003_check_in_date_check_in_uuid_alter_check_in_blockers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_in',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='prompt_message',
            old_name='user_id',
            new_name='user',
        ),
    ]
