# Generated by Django 4.0.6 on 2022-07-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0004_rename_user_id_check_in_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
