# Generated by Django 4.0.6 on 2022-07-25 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('slack', 'Slack'), ('jira', 'Jira')], max_length=5)),
                ('token', models.CharField(max_length=1350)),
                ('refresh_token', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket_status_changes',
            name='new_status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('testing', 'Testing'), ('done', 'Done')], max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket_status_changes',
            name='old_status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('testing', 'Testing'), ('done', 'Done')], max_length=12),
        ),
    ]
