# Generated by Django 4.0.6 on 2022-07-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_api_token_alter_ticket_status_changes_new_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_token',
            old_name='token_type',
            new_name='service',
        ),
    ]
